version: '3.9'
services:

  nrs:   
    container_name: nrs1
    public: true
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
   
    #volumes:
    #  - node-red:/home/94r4d0x/.node-red
    links:
      - mongodb

