version: '3.9'
services:

  nrs1:   
    #name: $NR_APP_NAME,
    public: true
    labels:
      app: sample
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - NR_ENV_ACCESS_PATH=/home/94r4d0x
        - NR_USER=94r4d0x
        - NR_DB_URL=${NR_DB_URL}
        - NR_APP_ID=${NR_APP_ID}
        - NR_DB_USER=${NR_DB_USER}
        - NR_DB_PASS=${NR_DB_PASS}
        - NR_DB_HOST=${NR_DB_HOST}
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
    ports:
      - 1880
   
    #volumes:
    #  - node-red:/home/94r4d0x/.node-red
    links:
      - mongodb

